version: '3.9'

services:
  client:
    container_name: client
    build:
      context: .
    ports:
      - '5173:5173'
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - queue-net

networks:
  queue-net:
    external: true
    name: queue-net
