version: "3.9"

services:
  # postgres:
  #   container_name: postgres_container
  #   image: "postgres:16"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - queue-net
  #   env_file:
  #     - ./.env.development
  #   restart: always
  #   ports:
  #     - "5432:5432"

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: docker/development/Dockerfile
    ports:
      - "5173:5173"
    restart: always
    env_file:
      - ./.env.development
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/package.json:/usr/src/app/package.json
    depends_on:
      - server
    networks:
      - queue-net

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: docker/development/Dockerfile
    ports:
      - "5000:5000"
      - "3000:3000"
    # depends_on:
    #   - postgres
    env_file:
      - ./.env.development
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/bot.js:/usr/src/app/bot.js
      - ./server/package.json:/usr/src/app/package.json
      - ./server/nodemon.json:/usr/src/app/nodemon.json
      - ./server/public:/usr/src/app/public
    networks:
      - queue-net

  admin:
    container_name: admin
    build:
      context: ./oneappAdmin
      dockerfile: docker/development/Dockerfile
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./.env.development
    volumes:
      - ./admin/src:/usr/src/app/src
      - ./admin/package.json:/usr/src/app/package.json
    depends_on:
      - server
    networks:
      - queue-net

networks:
  queue-net:
    driver: bridge

volumes:
  postgres-data:
