import Navbar from "../../../components/NavBar/NavBar";
import Footer from "../../../components/Footer/Footer";
import DisclaimerImg from "../../../assets/Disclaimer.png";

const Disclaimer = () => {
  return (
    <div className="min-h-screen bg-black text-white">
      {/* Navbar */}
      <Navbar />

      {/* Hero Section */}
      <section className="container mx-auto px-4 py-16 bg-black text-white">
        <div className="max-w-7xl mx-auto grid md:grid-cols-2 gap-16 items-center">
          <div className="space-y-8">
            <div className="inline-block px-4 py-2 bg-orange-500 text-white rounded-full text-sm font-medium">
              Important Information
            </div>
            <h1 className="text-5xl font-extrabold text-orange-500 tracking-tight">
              Disclaimer
              <span className="block text-xl text-gray-300 mt-3 font-normal">
                Contiks One Hub Technology Pvt. Ltd.
              </span>
              <p className="text-sm text-gray-400">
                Effective Date: 5 February 2025
              </p>
            </h1>
            <p className="text-xl text-gray-300 leading-relaxed">
              A structured statement outlining legal limitations,
              responsibilities, and user rights.
            </p>
            {/* <div>
              <button className="px-10 py-4 bg-orange-600 text-white font-semibold rounded-lg hover:bg-orange-700 transition duration-300 shadow-lg">
                View Full Policy
              </button>
            </div> */}
          </div>
          <div className="flex justify-center">
            <img
              src={DisclaimerImg}
              alt="Disclaimer Policy"
              className="w-80 h-80 rounded-2xl shadow-lg"
            />
          </div>
        </div>
      </section>

      {/* Disclaimer Content */}
      <section className="container mx-auto px-4 py-8 bg-black">
        <div className="max-w-7xl mx-auto bg-black p-12 shadow-lg">
          <div className="border-b border-orange-500 pb-6 mb-10">
            <h2 className="text-5xl font-bold text-orange-500">
              Disclaimer Details
            </h2>
          </div>

          <div className="space-y-8 text-gray-300 leading-relaxed">
            <p>
              The following disclaimer clarifies that **Contiks One Hub
              Technology Pvt Ltd (COHTPL), as an entity, shall not be held
              liable for any content or materials published or distributed by
              content creators on or through any app or website associated with
              us. By using our services, you acknowledge and accept the terms of
              this disclaimer.
            </p>
            <ul className="list-disc pl-6 space-y-3">
              <li>
                No Endorsement or Control: COHTPL provides a platform for
                content creators to share their work, opinions, and ideas.
                However, we do not endorse or take responsibility for the
                accuracy, legality, or quality of the content generated by these
                creators. The views and opinions expressed by content creators
                are solely their own and do not represent those of COHTPL.
              </li>
              <li>
                Third-Party Content: The content and materials published or
                distributed by content creators on or through any app or website
                associated with COHTPL may include links, references, or
                recommendations to third-party websites, products, or services.
                COHTPL does not endorse, guarantee, or assume any liability for
                the content, accuracy, legality, or availability of these
                third-party resources..
              </li>
              <li>
                User Discretion and Responsibility: Users of COHTPL's services
                understand and agree that they must exercise their own judgment
                and discretion when relying on any content or materials created
                by content creators. It is the responsibility of the user to
                verify the accuracy, completeness, and relevance of the
                information provided by content creators.
              </li>
              <li>
                No Warranty or Liability: COHTPL makes no warranties, express
                or implied, regarding the accuracy, completeness, or
                availability of any content or materials created by content
                creators. We disclaim all liability for any losses, damages, or
                harm arising from the use or reliance on such content or
                materials. This includes but is not limited to financial loss,
                reputational damage, or any other direct, indirect,
                consequential, or incidental damages.
              </li>
              <li>
                Content Creator Relationships: COHTPL may have professional
                relationships or partnerships with content creators, but these
                relationships do not influence or alter the independence,
                objectivity, or integrity of the content created by them. The
                responsibility for the accuracy and quality of their content
                rests solely with the respective content creators.
              </li>
              <li>
                Content Monitoring and Removal: While COHTPL strives to
                maintain a safe and reliable platform, we do not actively
                monitor all content created by content creators. While we
                reserve the right to remove or modify any content that violates
                our policies or terms of service, we do not assume liability for
                any content that remains accessible or has been removed.
              </li>
              <li>
                Indemnification: By using COHTPL's services, you agree to
                indemnify and hold harmless COHTPL, its employees, officers,
                directors, and affiliates from any claims, damages, losses,
                liabilities, or expenses arising out of or related to your use
                of the content or materials created by content creators.
              </li>
            </ul>
            <p>
              It is important to note that this disclaimer does not limit or
              exclude any liability that cannot be limited or excluded under
              applicable law. To the extent that any provision of this
              disclaimer is found to be invalid or unenforceable, the remaining
              provisions shall continue to be in effect.
            </p>

            <p>
              By using COHTPL's services, you acknowledge that you have read,
              understood, and agreed to this disclaimer in its entirety. If you
              do not agree with any part of this disclaimer, you should refrain
              from using COHTPL's services.
            </p>
          </div>
        </div>
      </section>

      {/* Footer */}
      <Footer />
    </div>
  );
};

export default Disclaimer;
