openapi: 3.0.0
info:
  title: One1App Admin API
  description: API documentation for Admin endpoints
  version: 1.0.0

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    Error:
      type: object
      properties:
        message:
          type: string

    PaginationMeta:
      type: object
      properties:
        total:
          type: integer
        page:
          type: integer
        limit:
          type: integer
        totalPages:
          type: integer

paths:
  /admin/users:
    post:
      summary: Create a new user
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                phoneNumber:
                  type: string
                name:
                  type: string
                goals:
                  type: string
                heardAboutUs:
                  type: string
                socialMedia:
                  type: string
                role:
                  type: string
                  enum: [User, Creator, Admin]
      responses:
        201:
          description: User created successfully
        400:
          description: Bad request
        403:
          description: Unauthorized
        500:
          description: Server error

    get:
      summary: Get all users with pagination
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
          description: Items per page
      responses:
        200:
          description: List of users
        403:
          description: Unauthorized
        500:
          description: Server error

  /admin/users/{id}:
    put:
      summary: Update a user
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                phoneNumber:
                  type: string
                name:
                  type: string
                goals:
                  type: string
                heardAboutUs:
                  type: string
                socialMedia:
                  type: string
                role:
                  type: string
      responses:
        200:
          description: User updated successfully
        403:
          description: Unauthorized
        500:
          description: Server error

    delete:
      summary: Delete a user
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: User deleted successfully
        403:
          description: Unauthorized
        500:
          description: Server error

  /admin/dashboard:
    get:
      summary: Get dashboard statistics
      security:
        - BearerAuth: []
      responses:
        200:
          description: Dashboard data
          content:
            application/json:
              schema:
                type: object
                properties:
                  revenue:
                    type: object
                    properties:
                      today:
                        type: number
                      total:
                        type: number
                      percentageChange:
                        type: number
                      chartData:
                        type: array
                  creators:
                    type: object
                    properties:
                      total:
                        type: integer
                      active:
                        type: integer
                      inactive:
                        type: integer
                      new:
                        type: integer
                      percentageChange:
                        type: number
                      leaderboard:
                        type: array
        403:
          description: Unauthorized
        500:
          description: Server error

  /admin/user-report:
    get:
      summary: Get user statistics report
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
          description: Items per page
      responses:
        200:
          description: User report data
          content:
            application/json:
              schema:
                type: object
                properties:
                  statistics:
                    type: object
                    properties:
                      totalUsers:
                        type: integer
                      verifiedUsers:
                        type: integer
                      pendingVerification:
                        type: integer
                      activeUsers:
                        type: integer
                      inactiveUsers:
                        type: integer
                  users:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            initial:
                              type: string
                            name:
                              type: string
                            email:
                              type: string
                            phone:
                              type: string
                            verificationStatus:
                              type: string
                            activityStatus:
                              type: string
                      meta:
                        $ref: '#/components/schemas/PaginationMeta'
        403:
          description: Unauthorized
        500:
          description: Server error

  /admin/products:
    get:
      summary: Get all products
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
          description: Items per page
      responses:
        200:
          description: List of products
        403:
          description: Unauthorized
        500:
          description: Server error

  /admin/payments:
    get:
      summary: Get all payments
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
          description: Items per page
      responses:
        200:
          description: List of payments
        403:
          description: Unauthorized
        500:
          description: Server error

  /admin/admins:
    post:
      summary: Create a new admin
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - phoneNumber
                - name
              properties:
                email:
                  type: string
                phoneNumber:
                  type: string
                name:
                  type: string
      responses:
        201:
          description: Admin created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  newUser:
                    type: object
        400:
          description: Email or phone number already exists
        500:
          description: Internal server error

    get:
      summary: Get all admins with pagination
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
          description: Items per page
      responses:
        200:
          description: List of admins
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        email:
                          type: string
                        phone:
                          type: string
                        name:
                          type: string
                        role:
                          type: string
                  meta:
                    $ref: '#/components/schemas/PaginationMeta'
        500:
          description: Internal server error

  /admin/admins/{id}:
    put:
      summary: Update an admin
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                phoneNumber:
                  type: string
                name:
                  type: string
      responses:
        200:
          description: Admin updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  updatedAdmin:
                    type: object
        500:
          description: Internal server error

    delete:
      summary: Delete an admin
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Admin deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        500:
          description: Internal server error
